### ISSUE TITLE
PNG image import problem

### ISSUE THREAD

**Issue by ghost** [TheSimplicityArchitect/NoSoft-Feedbacks#2]
Problem in Ideabox template when importing a PNG image in order to replace Nosoft logo by:
![your-logo](https://user-images.githubusercontent.com/3190881/37094917-bd0de278-2214-11e8-8f39-0532f4ace1ad.png)
A red question mark appears instead of my image:
![bug-import-image-png](https://user-images.githubusercontent.com/3190881/37094935-ca6392e2-2214-11e8-8261-f2bc36e8ccff.JPG)

**Comment by TheSimplicityArchitect** [comment]
Hi gusmal,
Yes we also noted this bug... We have fixed in the next version.

**Comment by TheSimplicityArchitect** [comment]
The problem came from the organisation of the picture file with respect to the application platform. The path was not managed to swicth between a windows application and an android application (and also Mac/iOS by the way). With the [v0.7.3](https://github.com/TheSimplicityArchitect/NoSoft-Feedbacks/milestone/2), the path management has been completly rethought and is now able to switch between different platforms regarding the organization of the picture files.

**Comment by TheSimplicityArchitect** [comment]
We are currently making some final portability test before closing this bug and releasing the [v0.7.3](https://github.com/TheSimplicityArchitect/NoSoft-Feedbacks/milestone/2)
